version: "3.8"

services:
  frontend:
    build: ./front
    container_name: frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./back
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://localhost:27017/unow-test-db
      - JWT_SECRET=unow-secret-key
      - JWT_EXPIRES_IN=1H
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: always

  mongodb:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
